### ISSUE TITLE
Research Hackaton

### ISSUE THREAD

**Issue by FWalkowicz** [knmlprz/CASSINI_ALT#3]
Twoim celem jest zagłębienie się w wytyczne Hackatonu CASSINI

- [x] Przeczytaj dostępne prezentacje oraz zrób z nich podsumowanie
- [x] Co potrzebujemy do poprawnego zatwierdzenia projektu( prezentacja, github itp.)
- [x] Ograniczenia co nie możemy robić

**Comment by Matixp40** [comment]
[Teambuilding.pdf](https://github.com/user-attachments/files/17874715/Teambuilding.pdf)
